### ISSUE TITLE
Emulator startet sich nicht

### ISSUE THREAD

**Issue by Ultimativ** [Ultimativ/Xamarin-Example-Programming#1]
David, bitte hilf mir .. Mein Emulator startet sich nicht.

Hier ist ein Ausschnitt von meinen Logs:

Log..

**Comment by davdeveloper** [comment]
VIelen Dank Jeremy,

ich habe hier die Lösung für dich!

int = alter;

**Comment by Ultimativ** [comment]
Bitte Herr Shoan Scharrer,

wenn sie das nächste mal Ihre Hilfe anbieten, helfen sie mir.

Ich habe das Problem selbst gelöst. 
Problem war: int = 0 + alter = 2;
weil 2 +  0 = 2.
